services:
  - type: web
    name: traveldb-api
    runtime: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./traveldbBackend/Dockerfile
    dockerContext: ./traveldbBackend
    buildFilter:
      paths:
        - traveldbBackend/**
    healthCheckPath: /api/health
