INSERT INTO Countries (country_id, country_name_en, is_schengen) VALUES
-- Schengen countries
('AT','Austria',TRUE),
('BE','Belgium',TRUE),
('CZ','Czech Republic',TRUE),
('DK','Denmark',TRUE),
('EE','Estonia',TRUE),
('FI','Finland',TRUE),
('FR','France',TRUE),
('DE','Germany',TRUE),
('GR','Greece',TRUE),
('HU','Hungary',TRUE),
('IS','Iceland',TRUE),
('IT','Italy',TRUE),
('LV','Latvia',TRUE),
('LI','Liechtenstein',TRUE),
('LT','Lithuania',TRUE),
('LU','Luxembourg',TRUE),
('MT','Malta',TRUE),
('NL','Netherlands',TRUE),
('NO','Norway',TRUE),
('PL','Poland',TRUE),
('PT','Portugal',TRUE),
('SK','Slovakia',TRUE),
('SI','Slovenia',TRUE),
('ES','Spain',TRUE),
('SE','Sweden',TRUE),
('CH','Switzerland',TRUE),
('HR','Croatia',TRUE),

-- Non-Schengen countries
('AF','Afghanistan',FALSE),
('AL','Albania',FALSE),
('DZ','Algeria',FALSE),
('AD','Andorra',FALSE),
('AO','Angola',FALSE),
('AG','Antigua and Barbuda',FALSE),
('AR','Argentina',FALSE),
('AM','Armenia',FALSE),
('AU','Australia',FALSE),
('AZ','Azerbaijan',FALSE),
('BS','Bahamas',FALSE),
('BH','Bahrain',FALSE),
('BD','Bangladesh',FALSE),
('BB','Barbados',FALSE),
('BY','Belarus',FALSE),
('BZ','Belize',FALSE),
('BJ','Benin',FALSE),
('BT','Bhutan',FALSE),
('BO','Bolivia',FALSE),
('BA','Bosnia and Herzegovina',FALSE),
('BW','Botswana',FALSE),
('BR','Brazil',FALSE),
('BN','Brunei',FALSE),
('BG','Bulgaria',FALSE),
('BF','Burkina Faso',FALSE),
('BI','Burundi',FALSE),
('KH','Cambodia',FALSE),
('CM','Cameroon',FALSE),
('CA','Canada',FALSE),
('CV','Cape Verde',FALSE),
('CF','Central African Republic',FALSE),
('TD','Chad',FALSE),
('CL','Chile',FALSE),
('CN','China',FALSE),
('CO','Colombia',FALSE),
('KM','Comoros',FALSE),
('CG','Congo',FALSE),
('CR','Costa Rica',FALSE),
('CI','Ivory Coast',FALSE),
('CU','Cuba',FALSE),
('CY','Cyprus',FALSE),
('DJ','Djibouti',FALSE),
('DM','Dominica',FALSE),
('DO','Dominican Republic',FALSE),
('EC','Ecuador',FALSE),
('EG','Egypt',FALSE),
('SV','El Salvador',FALSE),
('GQ','Equatorial Guinea',FALSE),
('ER','Eritrea',FALSE),
('ET','Ethiopia',FALSE),
('FJ','Fiji',FALSE),
('GA','Gabon',FALSE),
('GM','Gambia',FALSE),
('GE','Georgia',FALSE),
('GH','Ghana',FALSE),
('GD','Grenada',FALSE),
('GT','Guatemala',FALSE),
('GN','Guinea',FALSE),
('GW','Guinea-Bissau',FALSE),
('GY','Guyana',FALSE),
('HT','Haiti',FALSE),
('HN','Honduras',FALSE),
('HK','Hong Kong',FALSE),
('IN','India',FALSE),
('ID','Indonesia',FALSE),
('IR','Iran',FALSE),
('IQ','Iraq',FALSE),
('IE','Ireland',FALSE),
('IL','Israel',FALSE),
('JM','Jamaica',FALSE),
('JP','Japan',FALSE),
('JO','Jordan',FALSE),
('KZ','Kazakhstan',FALSE),
('KE','Kenya',FALSE),
('KI','Kiribati',FALSE),
('KW','Kuwait',FALSE),
('KG','Kyrgyzstan',FALSE),
('LA','Laos',FALSE),
('LB','Lebanon',FALSE),
('LS','Lesotho',FALSE),
('LR','Liberia',FALSE),
('LY','Libya',FALSE),
('MO','Macao',FALSE),
('MG','Madagascar',FALSE),
('MW','Malawi',FALSE),
('MY','Malaysia',FALSE),
('MV','Maldives',FALSE),
('ML','Mali',FALSE),
('MH','Marshall Islands',FALSE),
('MR','Mauritania',FALSE),
('MU','Mauritius',FALSE),
('MX','Mexico',FALSE),
('MD','Moldova',FALSE),
('MC','Monaco',FALSE),
('MN','Mongolia',FALSE),
('ME','Montenegro',FALSE),
('MA','Morocco',FALSE),
('MZ','Mozambique',FALSE),
('MM','Myanmar',FALSE),
('NA','Namibia',FALSE),
('NP','Nepal',FALSE),
('NZ','New Zealand',FALSE),
('NI','Nicaragua',FALSE),
('NE','Niger',FALSE),
('NG','Nigeria',FALSE),
('KP','North Korea',FALSE),
('MK','North Macedonia',FALSE),
('OM','Oman',FALSE),
('PK','Pakistan',FALSE),
('PA','Panama',FALSE),
('PG','Papua New Guinea',FALSE),
('PY','Paraguay',FALSE),
('PE','Peru',FALSE),
('PH','Philippines',FALSE),
('QA','Qatar',FALSE),
('RO','Romania',FALSE),
('RU','Russia',FALSE),
('RW','Rwanda',FALSE),
('SA','Saudi Arabia',FALSE),
('SN','Senegal',FALSE),
('RS','Serbia',FALSE),
('SG','Singapore',FALSE),
('SB','Solomon Islands',FALSE),
('SO','Somalia',FALSE),
('ZA','South Africa',FALSE),
('KR','South Korea',FALSE),
('SS','South Sudan',FALSE),
('LK','Sri Lanka',FALSE),
('SD','Sudan',FALSE),
('SR','Suriname',FALSE),
('SY','Syria',FALSE),
('TW','Taiwan',FALSE),
('TJ','Tajikistan',FALSE),
('TZ','Tanzania',FALSE),
('TH','Thailand',FALSE),
('TL','Timor-Leste',FALSE),
('TG','Togo',FALSE),
('TO','Tonga',FALSE),
('TT','Trinidad and Tobago',FALSE),
('TN','Tunisia',FALSE),
('TR','Turkey',FALSE),
('TM','Turkmenistan',FALSE),
('UG','Uganda',FALSE),
('UA','Ukraine',FALSE),
('AE','United Arab Emirates',FALSE),
('GB','United Kingdom',FALSE),
('US','United States',FALSE),
('UY','Uruguay',FALSE),
('UZ','Uzbekistan',FALSE),
('VE','Venezuela',FALSE),
('VN','Vietnam',FALSE),
('YE','Yemen',FALSE),
('ZM','Zambia',FALSE),
('ZW','Zimbabwe',FALSE);

INSERT INTO Airlines (airline_id, airline_name, country_id) VALUES
-- Europe
('DY','Norwegian Air Shuttle','NO'),
('SK','Scandinavian Airlines','SE'),
('LH','Lufthansa','DE'),
('AF','Air France','FR'),
('KL','KLM','NL'),
('BA','British Airways','GB'),
('IB','Iberia','ES'),
('AZ','ITA Airways','IT'),
('LX','Swiss International Air Lines','CH'),
('OS','Austrian Airlines','AT'),
('TP','TAP Air Portugal','PT'),
('AY','Finnair','FI'),
('EI','Aer Lingus','IE'),
('LO','LOT Polish Airlines','PL'),
('OK','Czech Airlines','CZ'),
('JU','Air Serbia','RS'),
('BT','airBaltic','LV'),
('FR','Ryanair','IE'),
('U2','easyJet','GB'),
('W6','Wizz Air','HU'),

-- North America
('AA','American Airlines','US'),
('DL','Delta Air Lines','US'),
('UA','United Airlines','US'),
('WN','Southwest Airlines','US'),
('AS','Alaska Airlines','US'),
('AC','Air Canada','CA'),
('WS','WestJet','CA'),

-- South America
('LA','LATAM Airlines','CL'),
('AV','Avianca','CO'),
('G3','Gol Transportes Aéreos','BR'),
('AR','Aerolineas Argentinas','AR'),

-- Middle East
('EK','Emirates','AE'),
('QR','Qatar Airways','QA'),
('EY','Etihad Airways','AE'),
('SV','Saudia','SA'),
('GF','Gulf Air','BH'),

-- Asia
('NH','All Nippon Airways','JP'),
('JL','Japan Airlines','JP'),
('KE','Korean Air','KR'),
('OZ','Asiana Airlines','KR'),
('CA','Air China','CN'),
('MU','China Eastern Airlines','CN'),
('CZ','China Southern Airlines','CN'),
('SQ','Singapore Airlines','SG'),
('TG','Thai Airways','TH'),
('AI','Air India','IN'),
('MH','Malaysia Airlines','MY'),
('GA','Garuda Indonesia','ID'),
('PR','Philippine Airlines','PH'),

-- Africa
('ET','Ethiopian Airlines','ET'),
('MS','EgyptAir','EG'),
('AT','Royal Air Maroc','MA'),
('SA','South African Airways','ZA'),
('KQ','Kenya Airways','KE'),

-- Oceania
('QF','Qantas','AU'),
('VA','Virgin Australia','AU'),
('NZ','Air New Zealand','NZ');
