INSERT INTO Countries (country_id, country_name_en, is_schengen) VALUES
-- Schengen countries
('AT','Austria',TRUE),
('BE','Belgium',TRUE),
('CZ','Czech Republic',TRUE),
('DK','Denmark',TRUE),
('EE','Estonia',TRUE),
('FI','Finland',TRUE),
('FR','France',TRUE),
('DE','Germany',TRUE),
('GR','Greece',TRUE),
('HU','Hungary',TRUE),
('IS','Iceland',TRUE),
('IT','Italy',TRUE),
('LV','Latvia',TRUE),
('LI','Liechtenstein',TRUE),
('LT','Lithuania',TRUE),
('LU','Luxembourg',TRUE),
('MT','Malta',TRUE),
('NL','Netherlands',TRUE),
('NO','Norway',TRUE),
('PL','Poland',TRUE),
('PT','Portugal',TRUE),
('SK','Slovakia',TRUE),
('SI','Slovenia',TRUE),
('ES','Spain',TRUE),
('SE','Sweden',TRUE),
('CH','Switzerland',TRUE),
('HR','Croatia',TRUE),

-- Non-Schengen countries
('AF','Afghanistan',FALSE),
('AL','Albania',FALSE),
('DZ','Algeria',FALSE),
('AD','Andorra',FALSE),
('AO','Angola',FALSE),
('AG','Antigua and Barbuda',FALSE),
('AR','Argentina',FALSE),
('AM','Armenia',FALSE),
('AU','Australia',FALSE),
('AZ','Azerbaijan',FALSE),
('BS','Bahamas',FALSE),
('BH','Bahrain',FALSE),
('BD','Bangladesh',FALSE),
('BB','Barbados',FALSE),
('BY','Belarus',FALSE),
('BZ','Belize',FALSE),
('BJ','Benin',FALSE),
('BT','Bhutan',FALSE),
('BO','Bolivia',FALSE),
('BA','Bosnia and Herzegovina',FALSE),
('BW','Botswana',FALSE),
('BR','Brazil',FALSE),
('BN','Brunei',FALSE),
('BG','Bulgaria',FALSE),
('BF','Burkina Faso',FALSE),
('BI','Burundi',FALSE),
('KH','Cambodia',FALSE),
('CM','Cameroon',FALSE),
('CA','Canada',FALSE),
('CV','Cape Verde',FALSE),
('CF','Central African Republic',FALSE),
('TD','Chad',FALSE),
('CL','Chile',FALSE),
('CN','China',FALSE),
('CO','Colombia',FALSE),
('KM','Comoros',FALSE),
('CG','Congo',FALSE),
('CR','Costa Rica',FALSE),
('CI','Ivory Coast',FALSE),
('CU','Cuba',FALSE),
('CY','Cyprus',FALSE),
('DJ','Djibouti',FALSE),
('DM','Dominica',FALSE),
('DO','Dominican Republic',FALSE),
('EC','Ecuador',FALSE),
('EG','Egypt',FALSE),
('SV','El Salvador',FALSE),
('GQ','Equatorial Guinea',FALSE),
('ER','Eritrea',FALSE),
('ET','Ethiopia',FALSE),
('FJ','Fiji',FALSE),
('GA','Gabon',FALSE),
('GM','Gambia',FALSE),
('GE','Georgia',FALSE),
('GH','Ghana',FALSE),
('GD','Grenada',FALSE),
('GT','Guatemala',FALSE),
('GN','Guinea',FALSE),
('GW','Guinea-Bissau',FALSE),
('GY','Guyana',FALSE),
('HT','Haiti',FALSE),
('HN','Honduras',FALSE),
('HK','Hong Kong',FALSE),
('IN','India',FALSE),
('ID','Indonesia',FALSE),
('IR','Iran',FALSE),
('IQ','Iraq',FALSE),
('IE','Ireland',FALSE),
('IL','Israel',FALSE),
('JM','Jamaica',FALSE),
('JP','Japan',FALSE),
('JO','Jordan',FALSE),
('KZ','Kazakhstan',FALSE),
('KE','Kenya',FALSE),
('KI','Kiribati',FALSE),
('KW','Kuwait',FALSE),
('KG','Kyrgyzstan',FALSE),
('LA','Laos',FALSE),
('LB','Lebanon',FALSE),
('LS','Lesotho',FALSE),
('LR','Liberia',FALSE),
('LY','Libya',FALSE),
('MO','Macao',FALSE),
('MG','Madagascar',FALSE),
('MW','Malawi',FALSE),
('MY','Malaysia',FALSE),
('MV','Maldives',FALSE),
('ML','Mali',FALSE),
('MH','Marshall Islands',FALSE),
('MR','Mauritania',FALSE),
('MU','Mauritius',FALSE),
('MX','Mexico',FALSE),
('MD','Moldova',FALSE),
('MC','Monaco',FALSE),
('MN','Mongolia',FALSE),
('ME','Montenegro',FALSE),
('MA','Morocco',FALSE),
('MZ','Mozambique',FALSE),
('MM','Myanmar',FALSE),
('NA','Namibia',FALSE),
('NP','Nepal',FALSE),
('NZ','New Zealand',FALSE),
('NI','Nicaragua',FALSE),
('NE','Niger',FALSE),
('NG','Nigeria',FALSE),
('KP','North Korea',FALSE),
('MK','North Macedonia',FALSE),
('OM','Oman',FALSE),
('PK','Pakistan',FALSE),
('PA','Panama',FALSE),
('PG','Papua New Guinea',FALSE),
('PY','Paraguay',FALSE),
('PE','Peru',FALSE),
('PH','Philippines',FALSE),
('QA','Qatar',FALSE),
('RO','Romania',FALSE),
('RU','Russia',FALSE),
('RW','Rwanda',FALSE),
('SA','Saudi Arabia',FALSE),
('SN','Senegal',FALSE),
('RS','Serbia',FALSE),
('SG','Singapore',FALSE),
('SB','Solomon Islands',FALSE),
('SO','Somalia',FALSE),
('ZA','South Africa',FALSE),
('KR','South Korea',FALSE),
('SS','South Sudan',FALSE),
('LK','Sri Lanka',FALSE),
('SD','Sudan',FALSE),
('SR','Suriname',FALSE),
('SY','Syria',FALSE),
('TW','Taiwan',FALSE),
('TJ','Tajikistan',FALSE),
('TZ','Tanzania',FALSE),
('TH','Thailand',FALSE),
('TL','Timor-Leste',FALSE),
('TG','Togo',FALSE),
('TO','Tonga',FALSE),
('TT','Trinidad and Tobago',FALSE),
('TN','Tunisia',FALSE),
('TR','Turkey',FALSE),
('TM','Turkmenistan',FALSE),
('UG','Uganda',FALSE),
('UA','Ukraine',FALSE),
('AE','United Arab Emirates',FALSE),
('GB','United Kingdom',FALSE),
('US','United States',FALSE),
('UY','Uruguay',FALSE),
('UZ','Uzbekistan',FALSE),
('VE','Venezuela',FALSE),
('VN','Vietnam',FALSE),
('YE','Yemen',FALSE),
('ZM','Zambia',FALSE),
('ZW','Zimbabwe',FALSE);

INSERT INTO Airlines (airline_id, airline_name, country_id) VALUES
-- Europe
('DY','Norwegian Air Shuttle','NO'),
('SK','Scandinavian Airlines','SE'),
('LH','Lufthansa','DE'),
('AF','Air France','FR'),
('KL','KLM','NL'),
('BA','British Airways','GB'),
('IB','Iberia','ES'),
('AZ','ITA Airways','IT'),
('LX','Swiss International Air Lines','CH'),
('OS','Austrian Airlines','AT'),
('TP','TAP Air Portugal','PT'),
('AY','Finnair','FI'),
('EI','Aer Lingus','IE'),
('LO','LOT Polish Airlines','PL'),
('OK','Czech Airlines','CZ'),
('JU','Air Serbia','RS'),
('BT','airBaltic','LV'),
('FR','Ryanair','IE'),
('U2','easyJet','GB'),
('W6','Wizz Air','HU'),

-- North America
('AA','American Airlines','US'),
('DL','Delta Air Lines','US'),
('UA','United Airlines','US'),
('WN','Southwest Airlines','US'),
('AS','Alaska Airlines','US'),
('AC','Air Canada','CA'),
('WS','WestJet','CA'),

-- South America
('LA','LATAM Airlines','CL'),
('AV','Avianca','CO'),
('G3','Gol Transportes Aéreos','BR'),
('AR','Aerolineas Argentinas','AR'),

-- Middle East
('EK','Emirates','AE'),
('QR','Qatar Airways','QA'),
('EY','Etihad Airways','AE'),
('SV','Saudia','SA'),
('GF','Gulf Air','BH'),

-- Asia
('NH','All Nippon Airways','JP'),
('JL','Japan Airlines','JP'),
('KE','Korean Air','KR'),
('OZ','Asiana Airlines','KR'),
('CA','Air China','CN'),
('MU','China Eastern Airlines','CN'),
('CZ','China Southern Airlines','CN'),
('SQ','Singapore Airlines','SG'),
('TG','Thai Airways','TH'),
('AI','Air India','IN'),
('MH','Malaysia Airlines','MY'),
('GA','Garuda Indonesia','ID'),
('PR','Philippine Airlines','PH'),

-- Africa
('ET','Ethiopian Airlines','ET'),
('MS','EgyptAir','EG'),
('AT','Royal Air Maroc','MA'),
('SA','South African Airways','ZA'),
('KQ','Kenya Airways','KE'),

('QF','Qantas','AU'),
('VA','Virgin Australia','AU'),
('NZ','Air New Zealand','NZ');

INSERT INTO Airports (iata_code, name, country, country_code, is_schengen) VALUES
('OSL','Oslo Airport Gardermoen','Norway','NO',TRUE),
('TRF','Sandefjord Airport Torp','Norway','NO',TRUE),
('ARN','Stockholm Arlanda','Sweden','SE',TRUE),
('BMA','Stockholm Bromma','Sweden','SE',TRUE),
('CPH','Copenhagen Airport','Denmark','DK',TRUE),
('HEL','Helsinki Airport','Finland','FI',TRUE),
('KEF','Keflavík International','Iceland','IS',TRUE),
('FRA','Frankfurt Airport','Germany','DE',TRUE),
('MUC','Munich Airport','Germany','DE',TRUE),
('BER','Berlin Brandenburg','Germany','DE',TRUE),
('CDG','Charles de Gaulle Airport','France','FR',TRUE),
('ORY','Paris Orly Airport','France','FR',TRUE),
('LYS','Lyon–Saint-Exupéry','France','FR',TRUE),
('AMS','Schiphol Airport','Netherlands','NL',TRUE),
('RTM','Rotterdam The Hague','Netherlands','NL',TRUE),
('MAD','Adolfo Suárez Madrid–Barajas','Spain','ES',TRUE),
('BCN','Barcelona–El Prat','Spain','ES',TRUE),
('AGP','Málaga–Costa del Sol','Spain','ES',TRUE),
('PMI','Palma de Mallorca','Spain','ES',TRUE),
('VIE','Vienna International','Austria','AT',TRUE),
('SZG','Salzburg Airport','Austria','AT',TRUE),
('ZRH','Zurich Airport','Switzerland','CH',TRUE),
('GVA','Geneva Airport','Switzerland','CH',TRUE),
('MXP','Milan Malpensa','Italy','IT',TRUE),
('LIN','Milan Linate','Italy','IT',TRUE),
('FCO','Rome Fiumicino','Italy','IT',TRUE),
('CIA','Rome Ciampino','Italy','IT',TRUE),
('LIS','Humberto Delgado Airport','Portugal','PT',TRUE),
('OPO','Francisco Sá Carneiro','Portugal','PT',TRUE),
('PRG','Václav Havel Airport Prague','Czech Republic','CZ',TRUE),
('BUD','Budapest Ferenc Liszt','Hungary','HU',TRUE),
('WAW','Warsaw Chopin','Poland','PL',TRUE),
('KRK','Kraków John Paul II','Poland','PL',TRUE),
('ATH','Athens International','Greece','GR',TRUE),
('SKG','Thessaloniki Airport','Greece','GR',TRUE),
('BRU','Brussels Airport','Belgium','BE',TRUE),
('CRL','Brussels South Charleroi','Belgium','BE',TRUE),
('LUX','Luxembourg Airport','Luxembourg','LU',TRUE),
('RIX','Riga International','Latvia','LV',TRUE),
('TLL','Tallinn Airport','Estonia','EE',TRUE),
('VNO','Vilnius Airport','Lithuania','LT',TRUE),
('ZAG','Zagreb Airport','Croatia','HR',TRUE),

('LHR','Heathrow Airport','United Kingdom','GB',FALSE),
('LGW','Gatwick Airport','United Kingdom','GB',FALSE),
('MAN','Manchester Airport','United Kingdom','GB',FALSE),
('EDI','Edinburgh Airport','United Kingdom','GB',FALSE),
('DUB','Dublin Airport','Ireland','IE',FALSE),
('SNN','Shannon Airport','Ireland','IE',FALSE),
('IST','Istanbul Airport','Turkey','TR',FALSE),
('SAW','Sabiha Gökçen','Turkey','TR',FALSE),
('BEG','Belgrade Nikola Tesla','Serbia','RS',FALSE),
('OTP','Henri Coandă International','Romania','RO',FALSE),
('SOF','Sofia Airport','Bulgaria','BG',FALSE),
('SJJ','Sarajevo International','Bosnia and Herzegovina','BA',FALSE),

('JFK','John F. Kennedy International','United States','US',FALSE),
('LGA','LaGuardia Airport','United States','US',FALSE),
('LAX','Los Angeles International','United States','US',FALSE),
('SFO','San Francisco International','United States','US',FALSE),
('SEA','Seattle–Tacoma International','United States','US',FALSE),
('ORD','O’Hare International','United States','US',FALSE),
('DEN','Denver International','United States','US',FALSE),
('ATL','Hartsfield–Jackson Atlanta','United States','US',FALSE),
('MIA','Miami International','United States','US',FALSE),
('BOS','Logan International','United States','US',FALSE),
('YYZ','Toronto Pearson','Canada','CA',FALSE),
('YUL','Montréal–Trudeau','Canada','CA',FALSE),
('YVR','Vancouver International','Canada','CA',FALSE),
('MEX','Mexico City International','Mexico','MX',FALSE),
('CUN','Cancún International','Mexico','MX',FALSE),

('HND','Haneda Airport','Japan','JP',FALSE),
('NRT','Narita International','Japan','JP',FALSE),
('KIX','Kansai International','Japan','JP',FALSE),
('PEK','Beijing Capital','China','CN',FALSE),
('PKX','Beijing Daxing','China','CN',FALSE),
('PVG','Shanghai Pudong','China','CN',FALSE),
('CAN','Guangzhou Baiyun','China','CN',FALSE),
('ICN','Incheon International','South Korea','KR',FALSE),
('GMP','Gimpo International','South Korea','KR',FALSE),
('SIN','Changi Airport','Singapore','SG',FALSE),
('HKG','Hong Kong International','Hong Kong','HK',FALSE),
('BKK','Suvarnabhumi Airport','Thailand','TH',FALSE),
('DMK','Don Mueang','Thailand','TH',FALSE),
('DEL','Indira Gandhi International','India','IN',FALSE),
('BOM','Chhatrapati Shivaji Maharaj','India','IN',FALSE),

('DXB','Dubai International','United Arab Emirates','AE',FALSE),
('DWC','Al Maktoum International','United Arab Emirates','AE',FALSE),
('DOH','Hamad International','Qatar','QA',FALSE),
('RUH','King Khalid International','Saudi Arabia','SA',FALSE),
('JED','King Abdulaziz International','Saudi Arabia','SA',FALSE),
('TLV','Ben Gurion Airport','Israel','IL',FALSE),

('SYD','Sydney Kingsford Smith','Australia','AU',FALSE),
('MEL','Melbourne Airport','Australia','AU',FALSE),
('BNE','Brisbane Airport','Australia','AU',FALSE),
('AKL','Auckland Airport','New Zealand','NZ',FALSE),

('JNB','O. R. Tambo International','South Africa','ZA',FALSE),
('CPT','Cape Town International','South Africa','ZA',FALSE),
('CAI','Cairo International','Egypt','EG',FALSE),
('CMN','Mohammed V International','Morocco','MA',FALSE),
('ADD','Addis Ababa Bole','Ethiopia','ET',FALSE),
('OSD','Åre Östersund Airport','Sweden','SE',TRUE),
('UME','Umeå Airport','Sweden','SE',TRUE),
('LLA','Luleå Airport','Sweden','SE',TRUE),
('TMP','Tampere–Pirkkala Airport','Finland','FI',TRUE),
('OUL','Oulu Airport','Finland','FI',TRUE),
('BGO','Bergen Airport Flesland','Norway','NO',TRUE),
('SVG','Stavanger Airport','Norway','NO',TRUE),
('TRD','Trondheim Airport Værnes','Norway','NO',TRUE),

('HAM','Hamburg Airport','Germany','DE',TRUE),
('DUS','Düsseldorf Airport','Germany','DE',TRUE),
('CGN','Cologne Bonn Airport','Germany','DE',TRUE),
('STR','Stuttgart Airport','Germany','DE',TRUE),
('NUE','Nuremberg Airport','Germany','DE',TRUE),

('TLS','Toulouse–Blagnac Airport','France','FR',TRUE),
('NCE','Nice Côte d’Azur Airport','France','FR',TRUE),
('MRS','Marseille Provence Airport','France','FR',TRUE),
('BOD','Bordeaux–Mérignac Airport','France','FR',TRUE),

('ALC','Alicante–Elche Airport','Spain','ES',TRUE),
('SVQ','Seville Airport','Spain','ES',TRUE),
('BIO','Bilbao Airport','Spain','ES',TRUE),
('TFS','Tenerife South Airport','Spain','ES',TRUE),
('LPA','Gran Canaria Airport','Spain','ES',TRUE),

('NAP','Naples International Airport','Italy','IT',TRUE),
('BLQ','Bologna Guglielmo Marconi Airport','Italy','IT',TRUE),
('VCE','Venice Marco Polo Airport','Italy','IT',TRUE),
('TRN','Turin Airport','Italy','IT',TRUE),

('BRI','Bari Karol Wojtyła Airport','Italy','IT',TRUE),
('PSA','Pisa International Airport','Italy','IT',TRUE),

-- UK & Ireland
('BHX','Birmingham Airport','United Kingdom','GB',FALSE),
('BRS','Bristol Airport','United Kingdom','GB',FALSE),
('LPL','Liverpool John Lennon','United Kingdom','GB',FALSE),
('GLA','Glasgow Airport','United Kingdom','GB',FALSE),

-- USA (expanded hubs + regionals)
('PHX','Phoenix Sky Harbor','United States','US',FALSE),
('DFW','Dallas/Fort Worth International','United States','US',FALSE),
('IAH','George Bush Intercontinental','United States','US',FALSE),
('LAS','Harry Reid International','United States','US',FALSE),
('MSP','Minneapolis–Saint Paul','United States','US',FALSE),
('DTW','Detroit Metropolitan','United States','US',FALSE),
('PHL','Philadelphia International','United States','US',FALSE),
('CLT','Charlotte Douglas','United States','US',FALSE),
('SAN','San Diego International','United States','US',FALSE),

-- Asia (expanded)
('CTU','Chengdu Shuangliu','China','CN',FALSE),
('TFU','Chengdu Tianfu','China','CN',FALSE),
('SZX','Shenzhen Bao’an','China','CN',FALSE),
('HGH','Hangzhou Xiaoshan','China','CN',FALSE),

('KUL','Kuala Lumpur International','Malaysia','MY',FALSE),
('CGK','Soekarno–Hatta International','Indonesia','ID',FALSE),
('HAN','Noi Bai International','Vietnam','VN',FALSE),
('SGN','Tan Son Nhat International','Vietnam','VN',FALSE),

-- Middle East
('AUH','Abu Dhabi International','United Arab Emirates','AE',FALSE),
('KWI','Kuwait International','Kuwait','KW',FALSE),
('MCT','Muscat International','Oman','OM',FALSE),

-- Africa
('LOS','Murtala Muhammed International','Nigeria','NG',FALSE),
('ACC','Kotoka International','Ghana','GH',FALSE),
('DAR','Julius Nyerere International','Tanzania','TZ',FALSE),

-- South America
('GRU','São Paulo–Guarulhos','Brazil','BR',FALSE),
('GIG','Rio de Janeiro–Galeão','Brazil','BR',FALSE),
('SCL','Arturo Merino Benítez','Chile','CL',FALSE),
('LIM','Jorge Chávez International','Peru','PE',FALSE),
('BOG','El Dorado International','Colombia','CO',FALSE);
