CREATE TABLE document_rule_datasets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_version VARCHAR(100) NOT NULL UNIQUE,
    generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    imported_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE active_document_rule_dataset (
    slot SMALLINT PRIMARY KEY,
    dataset_id BIGINT NOT NULL UNIQUE,
    CONSTRAINT chk_active_dataset_slot CHECK (slot = 1),
    CONSTRAINT fk_active_dataset FOREIGN KEY (dataset_id)
        REFERENCES document_rule_datasets(id)
);

CREATE TABLE document_rule_dataset_sources (
    dataset_id BIGINT NOT NULL,
    source_position INTEGER NOT NULL,
    label VARCHAR(300) NOT NULL,
    url VARCHAR(2000) NOT NULL,
    source_type VARCHAR(50) NOT NULL,
    PRIMARY KEY (dataset_id, source_position),
    FOREIGN KEY (dataset_id) REFERENCES document_rule_datasets(id) ON DELETE CASCADE
);

CREATE TABLE document_rules (
    dataset_id BIGINT NOT NULL,
    rule_id VARCHAR(200) NOT NULL,
    rule_position INTEGER NOT NULL,
    decision_key VARCHAR(200) NOT NULL,
    scope VARCHAR(30) NOT NULL,
    priority INTEGER NOT NULL,
    effective_from DATE,
    effective_to DATE,
    last_verified DATE NOT NULL,
    review_after DATE NOT NULL,
    minimum_age INTEGER,
    maximum_age INTEGER,
    output_code VARCHAR(200) NOT NULL,
    category VARCHAR(50) NOT NULL,
    output_status VARCHAR(50) NOT NULL,
    title VARCHAR(500) NOT NULL,
    summary VARCHAR(4000) NOT NULL,
    PRIMARY KEY (dataset_id, rule_id),
    UNIQUE (dataset_id, rule_position),
    FOREIGN KEY (dataset_id) REFERENCES document_rule_datasets(id) ON DELETE CASCADE,
    CONSTRAINT chk_document_rule_priority CHECK (priority >= 0),
    CONSTRAINT chk_document_rule_age_range CHECK (
        (minimum_age IS NULL OR minimum_age >= 0)
        AND (maximum_age IS NULL OR maximum_age >= 0)
        AND (minimum_age IS NULL OR maximum_age IS NULL OR minimum_age <= maximum_age)
    )
);

CREATE TABLE document_rule_selectors (
    dataset_id BIGINT NOT NULL,
    rule_id VARCHAR(200) NOT NULL,
    selector_type VARCHAR(60) NOT NULL,
    selector_position INTEGER NOT NULL,
    selector_value VARCHAR(100) NOT NULL,
    PRIMARY KEY (dataset_id, rule_id, selector_type, selector_position),
    FOREIGN KEY (dataset_id, rule_id) REFERENCES document_rules(dataset_id, rule_id) ON DELETE CASCADE
);

CREATE TABLE document_rule_conditions (
    dataset_id BIGINT NOT NULL,
    rule_id VARCHAR(200) NOT NULL,
    condition_position INTEGER NOT NULL,
    condition_text VARCHAR(2000) NOT NULL,
    PRIMARY KEY (dataset_id, rule_id, condition_position),
    FOREIGN KEY (dataset_id, rule_id) REFERENCES document_rules(dataset_id, rule_id) ON DELETE CASCADE
);

CREATE TABLE document_rule_sources (
    dataset_id BIGINT NOT NULL,
    rule_id VARCHAR(200) NOT NULL,
    source_position INTEGER NOT NULL,
    label VARCHAR(300) NOT NULL,
    url VARCHAR(2000) NOT NULL,
    source_type VARCHAR(50) NOT NULL,
    PRIMARY KEY (dataset_id, rule_id, source_position),
    FOREIGN KEY (dataset_id, rule_id) REFERENCES document_rules(dataset_id, rule_id) ON DELETE CASCADE
);

CREATE TABLE document_rule_key_facts (
    dataset_id BIGINT NOT NULL,
    rule_id VARCHAR(200) NOT NULL,
    fact_position INTEGER NOT NULL,
    label VARCHAR(300) NOT NULL,
    fact_value VARCHAR(2000) NOT NULL,
    PRIMARY KEY (dataset_id, rule_id, fact_position),
    FOREIGN KEY (dataset_id, rule_id) REFERENCES document_rules(dataset_id, rule_id) ON DELETE CASCADE
);

CREATE INDEX idx_document_rules_scope ON document_rules(dataset_id, scope);
CREATE INDEX idx_document_rules_decision ON document_rules(dataset_id, decision_key, priority);
CREATE INDEX idx_document_rule_selectors_value
    ON document_rule_selectors(dataset_id, selector_type, selector_value);
